const fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=path.join(__dirname,'..'),DB=path.join(ROOT,'db.json'),LEDGER=path.join(ROOT,'ledger.jsonl');
const POLICY={GENESIS_RESET_MIN_HOURS:24,GENESIS_RESET_WINDOW_HOURS:168};
const STARS=['twinkly','bright','twinkly','twinkly','bright','twinkly','final'];
const TABLES={night:[['Rare',85],['Epic',15]],twinkly:[['Common',80],['Uncommon',15],['Rare',4.98],['Epic',.02]],bright:[['Uncommon',60],['Rare',39.8],['Epic',.2]],final:[['Rare',65],['Epic',35]],milestone:[['Rare',15],['Epic',25],['Legendary',60]]};
const FOUNDATION=[['body','HERCULES','The Universe invites you to prepare your body.'],['mind','LYRA','The Universe invites you to prepare your mind.'],['heart','ANDROMEDA','The Universe invites you to prepare your heart.'],['soul','CYGNUS','The Universe invites you to prepare your soul.']].map(([id,name,invitation])=>({id,name,tier:'FOUNDATION',invitation}));
const HIDDEN={
 'spec-craft':{id:'spec-craft',name:'ORION',tier:'SPECIALIZATION',trigger:{type:'ORGANIC',sequence:['body-path-a','mind-path-a']},invitation:'The Universe invites you to refine what you can make.'},
 'spec-service':{id:'spec-service',name:'AQUILA',tier:'SPECIALIZATION',trigger:{type:'SPONSORED',eventCode:'PILOT-SERVICE'},invitation:'The Universe invites you to serve beyond yourself.'},
 'master-craft':{id:'master-craft',name:'PEGASUS',tier:'MASTERY',trigger:{type:'ORGANIC',sequence:['spec-craft-path-a','spec-craft-path-b']},invitation:'The Universe invites you to demonstrate mastery.'}
};
const PATHS={
 'body-path-a':{min:12},'body-path-b':{min:20,key:'prepare'},'mind-path-a':{min:12},'mind-path-b':{min:20,key:'practice'},'heart-path-a':{min:12},'heart-path-b':{min:20,key:'reflect'},'soul-path-a':{min:12},'soul-path-b':{min:20,key:'meaning'},
 'spec-craft-path-a':{min:24,key:'make'},'spec-craft-path-b':{min:24,key:'improve'},'spec-service-path-a':{min:24,key:'serve'},'master-craft-path-a':{min:32,key:'mastery'}
};
function seed(){return{version:3,series:{'GENESIS-I':{finite:true,max:100000,issued:0,closed:false}},travelers:{},livenessIndex:{},reviewFlags:[],reports:[],visits:[],ledgerHead:null}}
function save(d){fs.writeFileSync(DB,JSON.stringify(d,null,2))}function load(){try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{const d=seed();save(d);return d}}
function now(){return new Date().toISOString()}function id(p,n=5){return p+crypto.randomBytes(n).toString('hex').toUpperCase()}function hash(x){return crypto.createHash('sha256').update(x).digest('hex')}
function append(db,type,payload){const e={id:id('EV-',8),at:now(),type,payload,prevHash:db.ledgerHead||'GENESIS'};e.hash=hash(JSON.stringify({id:e.id,at:e.at,type:e.type,payload:e.payload,prevHash:e.prevHash}));fs.appendFileSync(LEDGER,JSON.stringify(e)+'\n');db.ledgerHead=e.hash;return e}
function verify(db){if(!fs.existsSync(LEDGER))return{ok:!db.ledgerHead,count:0};const lines=fs.readFileSync(LEDGER,'utf8').trim().split('\n').filter(Boolean);let prev='GENESIS';for(const l of lines){const e=JSON.parse(l),h=hash(JSON.stringify({id:e.id,at:e.at,type:e.type,payload:e.payload,prevHash:e.prevHash}));if(e.prevHash!==prev||e.hash!==h)return{ok:false,count:lines.length};prev=e.hash}return{ok:(db.ledgerHead||null)===(lines.length?prev:null),count:lines.length}}
function pick(t){let r=crypto.randomInt(0,1000000)/10000,a=0;for(const[n,p]of t){a+=p;if(r<a)return n}return t.at(-1)[0]}
function zodiac(m,d){const s=[20,19,21,20,21,21,23,23,23,23,22,22],n=['Capricorn','Aquarius','Pisces','Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius'];return d>=s[m-1]?n[m-1]:n[(m+10)%12]}
function cardIdentity(){const ds=[31,29,31,30,31,30,31,31,30,31,30,31],m=crypto.randomInt(1,13),d=crypto.randomInt(1,ds[m-1]+1);return{zodiac:zodiac(m,d),number:d}}
function issue(db,t,kind,hist){const s=db.series['GENESIS-I'];if(s.closed||s.issued>=s.max)throw Error('finite series closed');const rarity=(t.uniquePathCompletions===33&&kind==='final')?'Legendary':pick(TABLES[kind]||TABLES.twinkly),c={id:id('CARD-',7),series:'GENESIS-I',rarity,...cardIdentity(),ownerUid:t.uid,history:hist?[hist]:[],stamps:[],issuedAt:now()};t.cards.push(c);s.issued++;append(db,'CARD_ISSUED',{cardId:c.id,travelerUid:t.uid,rarity:c.rarity,kind});return c}
function invite(t,o){if(t.invitations.some(i=>i.key===o.id&&i.state!=='CONSUMED'))return null;const x={id:id('INV-'),key:o.id,domain:o.id,tier:o.tier,state:'NEW',text:o.invitation,createdAt:now()};t.invitations.push(x);return x}
function tier(domain){return FOUNDATION.some(x=>x.id===domain)?'FOUNDATION':HIDDEN[domain]?.tier||null}function def(domain){return FOUNDATION.find(x=>x.id===domain)||HIDDEN[domain]}
function completedPaths(t){return Object.values(t.journeys).filter(j=>j.status==='COMPLETED').map(j=>j.pathId)}
function seq(paths,want){let a=0;for(const p of paths){if(p===want[a])a++;if(a===want.length)return true}return false}
function organic(t){const paths=completedPaths(t);for(const o of Object.values(HIDDEN))if(o.trigger.type==='ORGANIC'&&seq(paths,o.trigger.sequence))invite(t,o)}
function assess(pathId,evidence){const c=PATHS[pathId]||{min:12},v=String(evidence||'').trim(),lo=v.toLowerCase();if(!v)return{outcome:'TRY_AGAIN',criterion:'Provide supported evidence.'};if(lo.includes('[review]')||lo.includes('[unclear]'))return{outcome:'REVIEW',criterion:'Evidence confidence is insufficient for automatic assessment.'};if(v.length<c.min)return{outcome:'TRY_AGAIN',criterion:`Evidence must contain at least ${c.min} observable characters.`};if(c.key&&!lo.includes(c.key))return{outcome:'TRY_AGAIN',criterion:`Observable criterion not found: ${c.key}.`};return{outcome:'PASS',criterion:'Defined observable criteria satisfied.'}}
function resetEligibility(t){if(t.genesisResetUsed)return{eligible:false,reason:'USED'};const age=(Date.now()-Date.parse(t.createdAt))/36e5;if(age<POLICY.GENESIS_RESET_MIN_HOURS)return{eligible:false,reason:'WAITING_INTERVAL'};if(age>POLICY.GENESIS_RESET_WINDOW_HOURS)return{eligible:false,reason:'WINDOW_EXPIRED'};return{eligible:true,reason:'ELIGIBLE'}}
function createTraveler(db,username,key){if(db.livenessIndex[key])return db.travelers[db.livenessIndex[key]];const t={uid:id('ST-',4),username,createdAt:now(),deleted:false,roles:['TRAVELER'],privacy:{cgPhoto:'PUBLIC'},blocks:[],cards:[],passport:[],constellations:{},invitations:[],journeys:{},uniquePathCompletions:0,firstLoreViewed:false,genesisResetUsed:false,milestone:null};db.travelers[t.uid]=t;db.livenessIndex[key]=t.uid;append(db,'TRAVELER_CREATED',{travelerUid:t.uid,username});issue(db,t,'night',{type:'GENESIS',historicalUsername:username,at:now()});FOUNDATION.forEach(o=>invite(t,o));return t}
function get(db,uid){const t=db.travelers[uid];if(!t)throw Error('traveler not found');return t}
function visibleSky(t){return Object.keys(t.constellations).map(domain=>{const s=t.constellations[domain],o=def(domain);return o?{id:domain,tier:o.tier,name:s.completed?o.name:null,completed:s.completed,stars:s.stars,actionable:true}:null}).filter(Boolean)}
function sanitize(db,t){return{uid:t.deleted?null:t.uid,username:t.deleted?'Former Traveler':t.username,roles:t.roles,firstLoreViewed:t.firstLoreViewed,invitations:t.invitations.filter(i=>i.state!=='CONSUMED'),visibleSky:visibleSky(t),cards:t.cards.map(c=>({id:c.id,series:c.series,rarity:c.rarity,zodiac:c.zodiac,number:c.number,boundJourneyId:c.boundJourneyId||null,stamps:c.stamps,history:c.history})),passport:t.passport,journeys:Object.values(t.journeys),milestone:t.milestone,privacy:t.privacy,genesisReset:resetEligibility(t),recentVisits:db.visits.filter(v=>v.targetUid===t.uid&&!t.blocks.includes(v.visitorUid)).sort((a,b)=>b.at.localeCompare(a.at)).filter((v,i,a)=>a.findIndex(x=>x.visitorUid===v.visitorUid)===i).slice(0,3).map(v=>{const x=db.travelers[v.visitorUid];return x&&!x.deleted?{uid:x.uid,username:x.username,at:v.at}:{username:'Former Traveler',at:v.at}})}}
function body(req){return new Promise((ok,bad)=>{let b='';req.on('data',c=>b+=c);req.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){bad(e)}})})}function send(res,s,o){const b=JSON.stringify(o);res.writeHead(s,{'Content-Type':'application/json','Content-Length':Buffer.byteLength(b)});res.end(b)}
async function handleApi(req,res,url){let db=load();if(!verify(db).ok)return send(res,500,{error:'ledger integrity failure'});const b=await body(req).catch(()=>({})),m=req.method,p=url.pathname;try{
 if(m==='POST'&&p==='/api/enroll'){if(!b.username||!b.livenessKey)return send(res,400,{error:'username and livenessKey required'});const t=createTraveler(db,String(b.username).slice(0,40),String(b.livenessKey).slice(0,120));save(db);return send(res,200,{traveler:sanitize(db,t),liveness:'VERIFIED_DEMO_ADAPTER'})}
 if(m==='POST'&&p==='/api/lore-viewed'){const t=get(db,b.uid);t.firstLoreViewed=true;save(db);return send(res,200,{ok:true})}
 if(m==='GET'&&p.startsWith('/api/state/'))return send(res,200,sanitize(db,get(db,decodeURIComponent(p.split('/').pop()))))
 if(m==='POST'&&p==='/api/username'){const t=get(db,b.uid),old=t.username;t.username=String(b.username||'').trim().slice(0,40);if(!t.username)throw Error('username required');append(db,'USERNAME_CHANGED',{travelerUid:t.uid,from:old,to:t.username});save(db);return send(res,200,{state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/invitation/accept'){const t=get(db,b.uid),i=t.invitations.find(x=>x.id===b.invitationId&&x.state!=='CONSUMED');if(!i)return send(res,404,{error:'invitation unavailable'});i.state='STANDING';if(!t.constellations[i.domain])t.constellations[i.domain]={stars:0,completed:false,tier:tier(i.domain)};save(db);return send(res,200,sanitize(db,t))}
 if(m==='GET'&&p==='/api/mirrors'){const t=get(db,url.searchParams.get('uid')),domain=url.searchParams.get('domain');if(!t.constellations[domain])return send(res,403,{error:'no active invitation'});const paths=[{id:domain+'-path-a',state:'AVAILABLE'},{id:domain+'-path-b',state:'AVAILABLE'}];Object.values(t.journeys).filter(j=>j.domain===domain&&j.status==='SUSPENDED').forEach(j=>paths.unshift({id:j.pathId,state:'SUSPENDED',journeyId:j.id,boundCardId:j.cardId}));return send(res,200,{paths:paths.map((x,i)=>({...x,vision:Array.from({length:5+i*3},(_,k)=>({status:k%4===0?'IN_PROGRESS':'COMPLETED'}))}))})}
 if(m==='POST'&&p==='/api/journey/start'){const t=get(db,b.uid);if(!t.constellations[b.domain])return send(res,403,{error:'invitation required'});const c=t.cards.find(x=>x.id===b.cardId&&x.ownerUid===t.uid);if(!c||c.boundJourneyId)return send(res,409,{error:'card unavailable'});const j={id:id('J-',6),domain:b.domain,tier:tier(b.domain),pathId:b.pathId,cardId:c.id,status:'ACTIVE',stars:0,createdAt:now(),awaitingCG:false};t.journeys[j.id]=j;c.boundJourneyId=j.id;append(db,'JOURNEY_STARTED',{travelerUid:t.uid,journeyId:j.id,pathId:j.pathId,cardId:j.cardId});save(db);return send(res,200,{journey:j,state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/journey/suspend'){const t=get(db,b.uid),j=t.journeys[b.journeyId];j.status='SUSPENDED';save(db);return send(res,200,{journey:j})}
 if(m==='POST'&&p==='/api/journey/complete-star'){const t=get(db,b.uid),j=t.journeys[b.journeyId];if(!j||j.awaitingCG)return send(res,409,{error:'journey unavailable'});const a=assess(j.pathId,b.evidence);if(a.outcome!=='PASS')return send(res,200,{assessment:a.outcome,criterion:a.criterion});const next=j.stars+1,isFinal=next===7,foundationDone=FOUNDATION.filter(x=>t.constellations[x.id]?.completed).length,needsCG=isFinal&&(j.tier!=='FOUNDATION'||foundationDone===3);if(needsCG){j.awaitingCG=true;j.status='AWAITING_CG';save(db);return send(res,200,{assessment:'PASS',awaitingCG:true})}const snap={travelerUid:t.uid,historicalUsername:t.username,journeyId:j.id,domain:j.domain,tier:j.tier,pathId:j.pathId,starIndex:next,at:now()},ev=append(db,'STAR_COMPLETED',snap),hist={...snap,ledgerEventId:ev.id};j.stars=next;t.constellations[j.domain].stars=Math.max(t.constellations[j.domain].stars,next);const reward=issue(db,t,STARS[next-1],hist),jc=t.cards.find(c=>c.id===j.cardId);if(jc)jc.history.push(hist);t.passport.push({summary:`${j.domain} · Star ${next} completed`,cardId:j.cardId,at:snap.at});if(isFinal){j.status='COMPLETED';t.constellations[j.domain].completed=true;if(jc)delete jc.boundJourneyId;t.uniquePathCompletions++;const inv=t.invitations.find(i=>i.domain===j.domain);if(inv)inv.state='STANDING';organic(t)}save(db);return send(res,200,{assessment:'PASS',reward,journey:j,state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/sponsored-event'){const t=get(db,b.uid),created=[];for(const o of Object.values(HIDDEN))if(o.trigger.type==='SPONSORED'&&o.trigger.eventCode===b.eventCode){const i=invite(t,o);if(i)created.push(i)}save(db);return send(res,200,{created,state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/cg/validate'){const g=get(db,b.guideUid),t=get(db,b.travelerUid),j=t.journeys[b.journeyId];if(!g.roles.includes('COMMUNITY_GUIDE'))return send(res,403,{error:'guide not authorized'});if(g.uid===t.uid)return send(res,403,{error:'self-authentication prohibited'});if(!j||!j.awaitingCG)return send(res,409,{error:'no CG-pending journey'});const snap={travelerUid:t.uid,historicalUsername:t.username,journeyId:j.id,domain:j.domain,tier:j.tier,pathId:j.pathId,starIndex:7,at:now()},ev=append(db,'CG_AUTHENTICATED_COMPLETION',{...snap,guideUid:g.uid,privacy:t.privacy.cgPhoto}),hist={...snap,ledgerEventId:ev.id,cg:{guideUid:g.uid,privacy:t.privacy.cgPhoto}};j.stars=7;j.awaitingCG=false;j.status='COMPLETED';t.constellations[j.domain].stars=7;t.constellations[j.domain].completed=true;t.uniquePathCompletions++;const jc=t.cards.find(c=>c.id===j.cardId);if(jc){jc.history.push(hist);delete jc.boundJourneyId}const reward=issue(db,t,'final',hist),inv=t.invitations.find(i=>i.domain===j.domain);if(inv)inv.state='STANDING';organic(t);if(FOUNDATION.every(x=>t.constellations[x.id]?.completed)&&!t.milestone){const milestone=issue(db,t,'milestone',{type:'FOUNDATIONAL_MILESTONE',historicalUsername:t.username,at:now()});t.milestone={cardId:milestone.id,stampPending:true}}save(db);return send(res,200,{reward,milestone:t.milestone,state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/stamp-choice'){const t=get(db,b.uid);if(!t.milestone?.stampPending)return send(res,409,{error:'no stamp choice pending'});const c=b.destination==='milestone'?t.cards.find(x=>x.id===t.milestone.cardId):t.cards.find(x=>x.id===b.journeyCardId);if(!c)return send(res,404,{error:'stamp target not found'});c.stamps.push({type:'FOUNDATIONAL',at:now()});append(db,'STAMP_APPLIED',{travelerUid:t.uid,cardId:c.id});t.milestone.stampPending=false;save(db);return send(res,200,{state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/block'){const t=get(db,b.uid);if(!t.blocks.includes(b.targetUid))t.blocks.push(b.targetUid);save(db);return send(res,200,{blocked:true})}
 if(m==='POST'&&p==='/api/report'){const t=get(db,b.uid),r={id:id('RPT-'),reporterUid:t.uid,targetUid:b.targetUid||null,reason:String(b.reason||'').slice(0,500),at:now(),status:'OPEN'};db.reports.push(r);append(db,'REPORT_CREATED',r);save(db);return send(res,200,{reportId:r.id,status:r.status})}
 if(m==='GET'&&p==='/api/travelers/find'){const q=(url.searchParams.get('q')||'').toLowerCase();return send(res,200,{results:Object.values(db.travelers).filter(t=>!t.deleted&&(t.uid.toLowerCase()===q||t.username.toLowerCase().includes(q))).slice(0,10).map(t=>({uid:t.uid,username:t.username}))})}
 if(m==='GET'&&p.startsWith('/api/traveler/public/')){const target=get(db,decodeURIComponent(p.split('/').pop())),viewer=url.searchParams.get('viewer');if(viewer&&target.blocks.includes(viewer))return send(res,403,{error:'blocked'});if(viewer&&viewer!==target.uid)db.visits.push({visitorUid:viewer,targetUid:target.uid,at:now()});save(db);return send(res,200,target.deleted?{uid:null,username:'Former Traveler',deleted:true}:{uid:target.uid,username:target.username,nightSky:visibleSky(target),archive:{passport:target.passport,binder:target.cards}})}
 if(m==='POST'&&p==='/api/privacy/cg-photo'){const t=get(db,b.uid);t.privacy.cgPhoto=b.value==='PRIVATE'?'PRIVATE':'PUBLIC';save(db);return send(res,200,{privacy:t.privacy})}
 if(m==='POST'&&p==='/api/genesis-reset'){const t=get(db,b.uid),e=resetEligibility(t);if(!e.eligible)return send(res,409,{error:'Genesis Reset not eligible',reason:e.reason});t.genesisResetUsed=true;t.passport=[];t.constellations={};t.invitations=[];t.journeys={};t.cards=t.cards.slice(0,1);FOUNDATION.forEach(o=>invite(t,o));append(db,'GENESIS_RESET_USED',{travelerUid:t.uid});save(db);return send(res,200,{state:sanitize(db,t)})}
 if(m==='POST'&&p==='/api/account/delete'){const t=get(db,b.uid);t.deleted=true;t.deletedAt=now();append(db,'ACCOUNT_DELETED',{travelerUid:t.uid,historicalUsername:t.username});save(db);return send(res,200,{ok:true,label:'Former Traveler',historyRetained:true})}
 if(m==='GET'&&p==='/api/integrity')return send(res,200,{ledger:verify(db),reports:db.reports.length,reviewFlags:db.reviewFlags.length})
 if(m==='POST'&&p==='/api/admin/seed-guide'){let g=Object.values(db.travelers).find(t=>t.roles.includes('COMMUNITY_GUIDE'));if(!g){g=createTraveler(db,'CommunityGuide','DEMO-GUIDE-HUMAN');g.roles.push('COMMUNITY_GUIDE');append(db,'ROLE_GRANTED',{travelerUid:g.uid,role:'COMMUNITY_GUIDE'});save(db)}return send(res,200,{guide:{uid:g.uid,username:g.username}})}
 return send(res,404,{error:'not found'})
 }catch(e){return send(res,500,{error:e.message})}}
function bootstrapIntegrity(){const db=load(),v=verify(db);if(!v.ok)throw Error('STELLAR provenance ledger integrity failure')}
module.exports={handleApi,bootstrapIntegrity};
